---
title: "Water Balloons"
author: "Isha Mehra and Shreya Punya"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r cars}
data <- data.frame(Score = c(12,
9,
0,
10,
8,
2,
4,
9,
1,
2,
1,
1,
14,
3,
7,
6,
0,
0,
2,
1,
4,
1,
4,
0,
6,
1,
3,
0,
1,
3,
4,
1,
6,
16,
4,
1,
0,
0,
8,
3,
1,
1,
3,
2,
0,
1,
6,
8,
7,
7,
1,
1,
7,
5,
14,
1))
```

Summary of Data:
```{r pressure, echo=FALSE}
summary(data)
```



```{r}
par(mfrow=c(1,2))
boxplot(data, main = "Boxplot of Scores")
hist(data$Score, main = "Distribution of Scores", xlab = "Score")
```

```{r fig.height = 7}
plot(x = 1:nrow(data), y = data$Score, xlab = "Water Balloon Count",
     ylab = "Tosses Until Break", main = "Water Balloon Toss Scores",
     col = ifelse(data$Score%%2==0, "red","blue"), cex.axis = .75)
legend("topright", legend=c("Shreya's Fault", "Isha's Fault"),
       col=c("blue", "red"), lty=1:2, cex=0.6)
abline(v = 2.5, col = "gray30", lty = 2)
text(x = 2.3, y = 12, labels = "Second Beer", pos = 4, cex = .65, col = "gray30")
abline(v = 20.5, col = "gray30", lty = 2)
text(x = 20.5, y = 12, labels = "Third Beer", pos = 4, cex = .65, col = "gray30")
abline(v = 36.5, col = "gray30", lty = 2)
text(x = 36.5, y = 12, labels = "Fourth Beer", pos = 4, cex = .65, col = "gray30")


```

